steps:
  # Backend build
  - name: 'python:3.13-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend/ikuchio-cup-2025
        pip install uv
        uv sync
        uv run pytest
    id: 'backend-test'

  # Frontend build
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd frontend/ikuchio-cup-2025
        npm ci
        npm run type-check
        npm run build-only
    id: 'frontend-build'

  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
    id: 'backend-docker-build'
    waitFor: ['backend-test']

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'
      - '-f'
      - 'frontend/Dockerfile'
      - '.'
    id: 'frontend-docker-build'
    waitFor: ['frontend-build']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA']
    id: 'backend-push'
    waitFor: ['backend-docker-build']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA']
    id: 'frontend-push'
    waitFor: ['frontend-docker-build']

images:
  - 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY