steps:
  # Build and push backend (combined)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/ikuchio-backend:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - 'backend/ikuchio-cup-2025/Dockerfile'
      - 'backend/ikuchio-cup-2025'
    id: 'backend-build'

  # Build and push frontend (combined)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/ikuchio-frontend:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - 'frontend/ikuchio-cup-2025/Dockerfile'
      - 'frontend/ikuchio-cup-2025'
    id: 'frontend-build'

  # Push images in parallel
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA']
    id: 'backend-push'
    waitFor: ['backend-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA']
    id: 'frontend-push'
    waitFor: ['frontend-build']

  # Deploy in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ikuchio-backend'
      - '--image=gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=API_KEY=google-vertexai-api-key:latest'
      - '--service-account=ikuchio-cicd@ikuchio-cup-2025.iam.gserviceaccount.com'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=ikuchio-cup-2025'
      - '--timeout=900'
      - '--port=8000'
      - '--cpu=2'
      - '--memory=2Gi'
      - '--max-instances=10'
      - '--min-instances=0'
    id: 'backend-deploy'
    waitFor: ['backend-push']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ikuchio-frontend'
      - '--image=gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=ikuchio-cicd@ikuchio-cup-2025.iam.gserviceaccount.com'
      - '--max-instances=10'
      - '--min-instances=0'
    id: 'frontend-deploy'
    waitFor: ['frontend-push']

images:
  - 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'

serviceAccount: 'projects/ikuchio-cup-2025/serviceAccounts/ikuchio-cicd@ikuchio-cup-2025.iam.gserviceaccount.com'

timeout: '300s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 50
  env:
    - 'DOCKER_BUILDKIT=1'