steps:
  # Build and push backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-backend:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/ikuchio-backend:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - 'backend/ikuchio-cup-2025/Dockerfile'
      - 'backend/ikuchio-cup-2025'
    id: 'backend-build'

  # Build and push frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ikuchio-frontend:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/ikuchio-frontend:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - 'frontend/ikuchio-cup-2025/Dockerfile'
      - 'frontend/ikuchio-cup-2025'
    id: 'frontend-build'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/ikuchio-backend']
    id: 'backend-push'
    waitFor: ['backend-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/ikuchio-frontend']
    id: 'frontend-push'
    waitFor: ['frontend-build']

  # Get GKE credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'ikuchio-cluster'
      - '--region=asia-northeast1'
    id: 'get-credentials'
    waitFor: ['-']

  # Create secret from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        API_KEY=$$(gcloud secrets versions access latest --secret="google-vertexai-api-key")
        kubectl create secret generic google-vertexai-api-key \
          --from-literal=key="$$API_KEY" \
          --namespace=ikuchio-cup-2025 \
          --dry-run=client -o yaml | kubectl apply -f -
    id: 'create-secret'
    waitFor: ['get-credentials']

  # Deploy to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update image tags in deployments
        sed -i "s|gcr.io/ikuchio-cup-2025/ikuchio-backend:latest|gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA|g" k8s/backend-deployment.yaml
        sed -i "s|gcr.io/ikuchio-cup-2025/ikuchio-frontend:latest|gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA|g" k8s/frontend-deployment.yaml
        
        # Apply all manifests
        kubectl apply -f k8s/
        
        # Wait for rollout
        kubectl rollout status deployment/ikuchio-backend -n ikuchio-cup-2025 --timeout=300s
        kubectl rollout status deployment/ikuchio-frontend -n ikuchio-cup-2025 --timeout=300s
    id: 'deploy-gke'
    waitFor: ['backend-push', 'frontend-push', 'create-secret']

images:
  - 'gcr.io/$PROJECT_ID/ikuchio-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ikuchio-frontend:$COMMIT_SHA'

serviceAccount: 'projects/ikuchio-cup-2025/serviceAccounts/ikuchio-cicd@ikuchio-cup-2025.iam.gserviceaccount.com'

timeout: '300s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 50
  env:
    - 'DOCKER_BUILDKIT=1'