apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikuchio-backend
  namespace: ikuchio-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ikuchio-backend
  template:
    metadata:
      labels:
        app: ikuchio-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/ikuchio-cup-2025/ikuchio-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: google-vertexai-api-key
              key: key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ikuchio-backend-service
  namespace: ikuchio-prod
spec:
  selector:
    app: ikuchio-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP