apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikuchio-frontend
  namespace: ikuchio-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ikuchio-frontend
  template:
    metadata:
      labels:
        app: ikuchio-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/ikuchio-cup-2025/ikuchio-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ikuchio-frontend-service
  namespace: ikuchio-prod
spec:
  selector:
    app: ikuchio-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP