apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikuchio-backend
  namespace: ikuchio-cup-2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikuchio-backend
  template:
    metadata:
      labels:
        app: ikuchio-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ikuchio-backend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: backend
        image: gcr.io/ikuchio-cup-2025/ikuchio-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "ikuchio-cup-2025"
        - name: ENVIRONMENT
          value: "production"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: google-vertexai-api-key
              key: key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"