apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikuchio-frontend
  namespace: ikuchio-cup-2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikuchio-frontend
  template:
    metadata:
      labels:
        app: ikuchio-frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ikuchio-frontend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: frontend
        image: gcr.io/ikuchio-cup-2025/ikuchio-frontend:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"