apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ikuchio-ingress
  namespace: ikuchio-cup-2025
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ikuchio-ip"
spec:
  ingressClassName: "gce"
  rules:
  - host: ikuchio-cup-2025.krz-tech.net
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ikuchio-frontend-service
            port:
              number: 80
  - host: api-ikuchio-cup-2025.krz-tech.net
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-lb
            port:
              number: 8000